- name: "install hadoop tarball"
  unarchive: src={{ tarballs_dir }}/{{ hadoop_tarball }} dest={{ install_dir }} creates={{ hadoop_prefix }} copy=yes
- name: "configure hadoop with templates"
  template: src={{ item }} dest={{ hadoop_prefix }}/etc/hadoop/{{ item }}
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - mapred-site.xml
    - slaves
- name: "configure hadoop with files"
  copy: src=capacity-scheduler.xml dest={{ hadoop_prefix }}/etc/hadoop/capacity-scheduler.xml
- name: "copy spark yarn shuffle jar to hadoop lib"
  command: cp {{ spark_home }}/lib/spark-{{ spark_version }}-yarn-shuffle.jar {{ hadoop_prefix }}/share/hadoop/yarn/lib/ creates={{ hadoop_prefix }}/share/hadoop/yarn/lib/spark-{{ spark_version }}-yarn-shuffle.jar
- name: "setup hadoop short circuit socket dir"
  file: path=/var/lib/hadoop-hdfs state=directory owner={{ cluster_user }} group={{ cluster_user }} mode=0755
  become: yes
