#
# Licensed to the Apache Software Foundation (ASF) under one or more contributor license
# agreements. See the NOTICE file distributed with this work for additional information regarding
# copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the License. You may obtain a
# copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

- name: "determine best apache mirror to use"
  shell: curl -sk https://apache.org/mirrors.cgi?as_json | grep preferred | cut -d \" -f 4
  args:
    warn: no
  register: apache_mirror
  failed_when: "'http' not in apache_mirror.stdout"
  changed_when: False
- name: "check if Spark tarball was uploaded to proxy"
  stat: path={{ tarballs_dir }}/{{ spark_tarball }}
  register: spark
- name: "download Spark tarball to proxy"
  get_url: url={{ item.urlp }}/{{ item.fn }} dest={{ tarballs_dir }}/{{ item.fn }} sha256sum={{ item.sum }} force=no
  register: gresult
  until: "'OK' in gresult.msg or 'file already exists' in gresult.msg"
  retries: 3
  with_items:
    - { urlp: "{{ apache_mirror.stdout }}/spark/spark-{{ spark_version }}", fn: "{{ spark_tarball }}", sum: "{{ spark_sha256 }}" }
  when: spark.stat.exists == False
