- name: "unmount default drive at /mnt"
  mount: name=/mnt src=/dev/xvdb fstype=auto state=unmounted
  when: cloud_provider == 'ec2'
- name: "mount drives"
  mount: name={{ item.0 }} src={{ item.1 }} fstype=auto state=mounted
    opts=defaults,nofail,noatime,nodiratime,comment=cloudconfig passno=2
  when: cloud_provider == 'ec2'
  with_together: 
    - "{{ node_type_map[node_type].mounts }}"
    - "{{ node_type_map[node_type].devices }}"
- name: "ensure drives are owned by cluster user"
  file: path={{ item }} state=directory owner={{ cluster_user }} group={{ cluster_user }} 
  with_items: "{{ node_type_map[node_type].mounts }}"
