#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: "ensure cluster user exists but don't generate ssh key"
  user: name={{ cluster_user }} generate_ssh_key=no state=present
- name: "copy cluster private key to all nodes"
  copy: src=/home/{{ cluster_user }}/.ssh/id_rsa dest=/home/{{ cluster_user }}/.ssh/id_rsa owner={{ cluster_user }} group={{ cluster_group }} mode=0600
- name: "copy cluster public key to all nodes"
  copy: src=/home/{{ cluster_user }}/.ssh/id_rsa.pub dest=/home/{{ cluster_user }}/.ssh/id_rsa.pub owner={{ cluster_user }} group={{ cluster_group }} mode=0644
- name: "add cluster user to ~/.ssh/authorized_keys"
  authorized_key: user={{ cluster_user }} key="{{ lookup('file', '/home/' + cluster_user + '/.ssh/id_rsa.pub') }}"
- name: "add conf/keys to ~/.ssh/authorized_keys"
  authorized_key: user={{ cluster_user }} key="{{ lookup('file', 'conf/keys') }}"
- name: "set ssh config"
  copy: src=roles/common/files/ssh_config dest=/home/{{ cluster_user }}/.ssh/config owner={{ cluster_user }} group={{ cluster_group }} mode=0600
