# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

export JAVA_HOME={{ java_home }}
export HADOOP_PREFIX={{ hadoop_prefix }}
export HADOOP_HOME=$HADOOP_PREFIX
export HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop
export ZOOKEEPER_HOME={{ zookeeper_home }}
export SPARK_HOME={{ spark_home }}
export ACCUMULO_HOME={{ accumulo_home }}
export FLUO_HOME={{ fluo_home }}
export FLUO_YARN_HOME={{ fluo_yarn_home }}

alias ssh='ssh -A'
alias cdh='cd {{ hadoop_prefix }}'
alias cdz='cd {{ zookeeper_home }}'
alias cda='cd {{ accumulo_home }}'
alias cdf='cd {{ fluo_home }}'
alias ashell='{{ accumulo_home }}/bin/accumulo shell -u root -p {{ accumulo_password }}'
