#!/usr/bin/env bash
ansible-galaxy collection install community.general==7.5.0
ansible-galaxy collection install azure.azcollection==1.18.1
pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
