- hosts: all
  roles:
    - accumulo
- hosts: accumulomaster
  tasks:
    - include: roles/accumulo/tasks/init-accumulo.yml
  handlers:
    - include: roles/accumulo/handlers/init-accumulo.yml
- hosts: accumulo
  tasks:
    - name: "start accumulo 1.0"
      command: "{{ accumulo_home }}/bin/start-here.sh"
      register: start_result
      changed_when: "'Starting' in start_result.stdout"
      when: accumulo_major_version == '1'
- hosts: workers
  tasks:
    - name: "start accumulo 2.0 tablet servers"
      command: "{{ accumulo_home }}/bin/accumulo-service tserver start"
      register: start_result
      changed_when: "'Starting' in start_result.stdout"
      when: accumulo_major_version == '2'
- hosts: accumulomaster
  tasks:
    - name: "start accumulo 2.0 master, monitor, gc & tracer"
      command: "{{ accumulo_home }}/bin/accumulo-service {{ item }} start"
      register: start_result
      changed_when: "'Starting' in start_result.stdout"
      with_items:
        - master
        - monitor
        - gc
        - tracer
      when: accumulo_major_version == '2'
