- hosts: nodes
  become: yes
  tasks:
    - import_tasks: roles/common/tasks/hosts.yml
- hosts: proxy
  roles:
    - proxy
- hosts: all
  become: yes
  roles:
    - common
  tasks:
    - import_tasks: roles/common/tasks/ssh.yml
    - import_tasks: roles/common/tasks/os.yml
    - import_tasks: roles/common/tasks/drives.yml
