---
#
# Playbook to install the ELK stack + Beats
#
- hosts: all:!{{ azure_proxy_host }}
  roles:
    - { role: elasticsearch }
    - { role: filebeat }
    - { role: kibana }
    - { role: logstash }
