
export JAVA_HOME=$cluster.base.dir/install/jdk1.8.0_60

PATH="$$JAVA_HOME/bin:$$PATH"
PATH="$cluster.base.dir/install/fluo-cluster/bin:$$PATH"
PATH="$cluster.base.dir/install/fluo-$fluo.version/bin:$$PATH"
PATH="$HADOOP_PREFIX/bin:$$PATH"
PATH="$HADOOP_PREFIX/sbin:$$PATH"
PATH="$cluster.base.dir/install/accumulo-$accumulo.version/bin:$$PATH"
PATH="$cluster.base.dir/install/maven/bin:$$PATH"
PATH="$cluster.base.dir/install/spark-$spark.version/bin:$$PATH"
PATH="$ZOOKEEPER_HOME/bin:$$PATH"
export PATH

alias ssh='ssh -A'
alias cdh='cd $HADOOP_PREFIX'
alias cdz='cd $ZOOKEEPER_HOME'
alias cda='cd $cluster.base.dir/install/accumulo-$accumulo.version'
alias cdf='cd $cluster.base.dir/install/fluo-$fluo.version'
alias ashell='fluo-cluster ashell'
