
export JAVA_HOME=$BASE_DIR/install/jdk1.7.0_75
export PATH=$$JAVA_HOME/bin:$BASE_DIR/install/fluo-cluster/bin:$BASE_DIR/install/fluo-$FLUO_VERSION/bin:$HADOOP_PREFIX/bin:$$PATH

alias ssh='ssh -A'
alias cdh='cd $HADOOP_PREFIX'
alias cdz='cd $BASE_DIR/install/zookeeper-$ZOOKEEPER_VERSION'
alias cda='cd $BASE_DIR/install/accumulo-$ACCUMULO_VERSION'
alias cdf='cd $BASE_DIR/install/fluo-$FLUO_VERSION'
