- name: "determine best apache mirror to use"
  shell: curl -sk https://apache.org/mirrors.cgi?as_json | jq -r .preferred
  args:
    warn: no
  register: apache_mirror
  retries: 10
  delay: 10
  until: "apache_mirror.stdout | length > 0"
  changed_when: False
